Install locales before running locale-gen
ThundeRatz/container-deploy pull request #8
Opened 2018-06-05 20:38 UTC by erickotsuka

Estava ocorrendo um erro ao rodar locale-gen. Isso resolveu.

2018-06-05 20:52 UTC, tiagoshibata commented
Acho que foi alguma mudança recente em qual pacote contém locales no Ubuntu, lembro de mudar algo assim em um container meu que quebrou.

Segue o mesmo formato dos outros `apt-get` (coloca `rm -rf /var/lib/apt/lists/*` depois da instalação pra não salvar o índice do apt nessa layer do docker, que ocuparia espaço desnecessariamente). Eu faria:

```
# General setup
RUN apt-get update && apt-get install --no-install-recommends -y build-essential locales sudo \
    && rm -rf /var/lib/apt/lists/*
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
```

2018-06-05 20:53 UTC, tiagoshibata requested changes
Acho que foi alguma mudança recente em qual pacote contém locales no Ubuntu, lembro de mudar algo assim em um container meu que quebrou.

Segue o mesmo formato dos outros `apt-get` (coloca `rm -rf /var/lib/apt/lists/*` depois da instalação pra não salvar o índice do apt nessa layer do docker, que ocuparia espaço desnecessariamente). Eu faria:

```
# General setup
RUN apt-get update && apt-get install --no-install-recommends -y build-essential locales sudo \
    && rm -rf /var/lib/apt/lists/*
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
```

2018-06-06 11:34 UTC, freitas-renato approved these changes

2018-06-06 16:03 UTC, tiagoshibata commented
Toop

2018-06-06 16:04 UTC, tiagoshibata approved these changes

2018-06-06 16:04 UTC, tiagoshibata commented
Top

2018-06-09 01:01 UTC, merged